// This file will be auto-generated by Supabase
// For now, we'll create placeholder types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      interactions: {
        Row: {
          id: string
          user_id: string
          input: string
          tool_calls: Json
          result: Json
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          input: string
          tool_calls?: Json
          result?: Json
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          input?: string
          tool_calls?: Json
          result?: Json
          created_at?: string
        }
      }
      knowledge: {
        Row: {
          id: string
          user_id: string
          content: string
          url: string
          embedding: number[]
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          content: string
          url: string
          embedding?: number[]
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          content?: string
          url?: string
          embedding?: number[]
          metadata?: Json
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}